mixed-port: 10801
allow-lan: true
bind-address: "*"
find-process-mode: strict

mode: rule

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"

log-level: debug

ipv6: false

dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 1.1.1.1
  enhanced-mode: fake-ip

  fake-ip-range: 198.10.0.1/16

proxies:
  - name: Vision
    type: vless
    server: 
    port: 
    uuid: chika
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: 
    client-fingerprint: chrome

  - name: Vision-REALITY
    type: vless
    server: 
    port: 
    uuid: chika
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.lovelive-anime.jp
    reality-opts:
      public-key: Z84J2IelR9ch3k8VtlVhhs5ycBUlXA7wHBWcBrjqnAw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome

  - name: gRPC-REALITY
    type: vless
    server: 
    port: 
    uuid: chika
    network: grpc
    tls: true
    udp: true
    flow: null
    servername: www.lovelive-anime.jp
    grpc-opts:
      grpc-service-name: grpc
    reality-opts:
      public-key: Z84J2IelR9ch3k8VtlVhhs5ycBUlXA7wHBWcBrjqnAw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome

  - name: H2-REALITY
    type: vless
    server: 
    port: 
    uuid: chika
    network: h2
    tls: true
    udp: true
    flow: null
    servername: www.lovelive-anime.jp
    reality-opts:
      public-key: Z84J2IelR9ch3k8VtlVhhs5ycBUlXA7wHBWcBrjqnAw
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Vision
      - Vision-REALITY
      - gRPC-REALITY
      - H2-REALITY

rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT,no-resolve
  - MATCH,PROXY
